-- Sync skill catalog categories with server/src/config/defaultSkills.ts
UPDATE "SkillCatalog" AS sc
SET category = v.category
FROM (VALUES
  ('JavaScript', 'Languages'),
  ('TypeScript', 'Languages'),
  ('Python', 'Languages'),
  ('Java', 'Languages'),
  ('C#', 'Languages'),
  ('C++', 'Languages'),
  ('Go', 'Languages'),
  ('Rust', 'Languages'),
  ('Kotlin', 'Languages'),
  ('Swift', 'Languages'),
  ('PHP', 'Languages'),
  ('Ruby', 'Languages'),
  ('Scala', 'Languages'),
  ('R', 'Languages'),
  ('Perl', 'Languages'),
  ('Objective-C', 'Languages'),
  ('Dart', 'Languages'),
  ('Elixir', 'Languages'),
  ('Haskell', 'Languages'),
  ('Lua', 'Languages'),
  ('Groovy', 'Languages'),
  ('Clojure', 'Languages'),
  ('Visual Basic', 'Languages'),
  ('COBOL', 'Languages'),
  ('PowerShell', 'Languages'),
  ('Shell Scripting', 'Languages'),
  ('Bash', 'Languages'),
  ('SQL', 'Languages'),
  ('PL/SQL', 'Languages'),
  ('React', 'Frontend'),
  ('Next.js', 'Frontend'),
  ('Angular', 'Frontend'),
  ('Vue.js', 'Frontend'),
  ('Svelte', 'Frontend'),
  ('SvelteKit', 'Frontend'),
  ('Ember.js', 'Frontend'),
  ('jQuery', 'Frontend'),
  ('HTML', 'Frontend'),
  ('CSS', 'Frontend'),
  ('Tailwind CSS', 'Frontend'),
  ('Bootstrap', 'Frontend'),
  ('Material UI', 'Frontend'),
  ('SASS', 'Frontend'),
  ('Redux', 'Frontend'),
  ('Web Components', 'Frontend'),
  ('Responsive Design', 'Frontend'),
  ('Node.js', 'Backend'),
  ('Express', 'Backend'),
  ('NestJS', 'Backend'),
  ('Django', 'Backend'),
  ('Flask', 'Backend'),
  ('FastAPI', 'Backend'),
  ('Spring Boot', 'Backend'),
  ('.NET', 'Backend'),
  ('ASP.NET Core', 'Backend'),
  ('Laravel', 'Backend'),
  ('Ruby on Rails', 'Backend'),
  ('GraphQL', 'Backend'),
  ('REST APIs', 'Backend'),
  ('gRPC', 'Backend'),
  ('Microservices', 'Backend'),
  ('Serverless', 'Backend'),
  ('API Development', 'Backend'),
  ('Full Stack Development', 'Backend'),
  ('Prisma', 'Backend'),
  ('Supabase', 'Backend'),
  ('Firebase', 'Backend'),
  ('React Native', 'Mobile'),
  ('Flutter', 'Mobile'),
  ('Android', 'Mobile'),
  ('iOS', 'Mobile'),
  ('SwiftUI', 'Mobile'),
  ('Xamarin', 'Mobile'),
  ('Mobile Development', 'Mobile'),
  ('PostgreSQL', 'Data'),
  ('MySQL', 'Data'),
  ('MariaDB', 'Data'),
  ('MongoDB', 'Data'),
  ('Redis', 'Data'),
  ('Elasticsearch', 'Data'),
  ('DynamoDB', 'Data'),
  ('Cassandra', 'Data'),
  ('Oracle Database', 'Data'),
  ('SQL Server', 'Data'),
  ('Neo4j', 'Data'),
  ('Snowflake', 'Data'),
  ('dbt', 'Data'),
  ('Apache Spark', 'Data'),
  ('Hadoop', 'Data'),
  ('Kafka', 'Data'),
  ('Apache Airflow', 'Data'),
  ('ETL', 'Data'),
  ('Data Analysis', 'Data'),
  ('Data Engineering', 'Data'),
  ('Data Warehousing', 'Data'),
  ('Database Administration', 'Data'),
  ('Machine Learning', 'Data Science'),
  ('Deep Learning', 'Data Science'),
  ('TensorFlow', 'Data Science'),
  ('PyTorch', 'Data Science'),
  ('Scikit-learn', 'Data Science'),
  ('Pandas', 'Data Science'),
  ('NumPy', 'Data Science'),
  ('NLP', 'Data Science'),
  ('Computer Vision', 'Data Science'),
  ('Generative AI', 'Data Science'),
  ('LLMs', 'Data Science'),
  ('MLOps', 'Data Science'),
  ('Tableau', 'Analytics'),
  ('Power BI', 'Analytics'),
  ('Looker', 'Analytics'),
  ('Excel', 'Analytics'),
  ('Google Analytics', 'Analytics'),
  ('Business Intelligence', 'Analytics'),
  ('AWS', 'Cloud & DevOps'),
  ('Azure', 'Cloud & DevOps'),
  ('Google Cloud', 'Cloud & DevOps'),
  ('Docker', 'Cloud & DevOps'),
  ('Kubernetes', 'Cloud & DevOps'),
  ('Terraform', 'Cloud & DevOps'),
  ('Ansible', 'Cloud & DevOps'),
  ('Puppet', 'Cloud & DevOps'),
  ('Chef', 'Cloud & DevOps'),
  ('CI/CD', 'Cloud & DevOps'),
  ('Jenkins', 'Cloud & DevOps'),
  ('GitHub Actions', 'Cloud & DevOps'),
  ('GitLab CI', 'Cloud & DevOps'),
  ('CircleCI', 'Cloud & DevOps'),
  ('Azure DevOps', 'Cloud & DevOps'),
  ('ArgoCD', 'Cloud & DevOps'),
  ('GitOps', 'Cloud & DevOps'),
  ('Apache', 'Cloud & DevOps'),
  ('Nginx', 'Cloud & DevOps'),
  ('Helm', 'Cloud & DevOps'),
  ('Prometheus', 'Cloud & DevOps'),
  ('Grafana', 'Cloud & DevOps'),
  ('ELK Stack', 'Cloud & DevOps'),
  ('Splunk', 'Cloud & DevOps'),
  ('Datadog', 'Cloud & DevOps'),
  ('New Relic', 'Cloud & DevOps'),
  ('Nagios', 'Cloud & DevOps'),
  ('Zabbix', 'Cloud & DevOps'),
  ('Vagrant', 'Cloud & DevOps'),
  ('Packer', 'Cloud & DevOps'),
  ('CloudFormation', 'Cloud & DevOps'),
  ('Pulumi', 'Cloud & DevOps'),
  ('Nomad', 'Cloud & DevOps'),
  ('Istio', 'Cloud & DevOps'),
  ('OpenShift', 'Cloud & DevOps'),
  ('AWS Lambda', 'Cloud & DevOps'),
  ('Infrastructure as Code', 'Cloud & DevOps'),
  ('Site Reliability Engineering', 'Cloud & DevOps'),
  ('DevOps', 'Cloud & DevOps'),
  ('Release Management', 'Cloud & DevOps'),
  ('SonarQube', 'Cloud & DevOps'),
  ('Nexus', 'Cloud & DevOps'),
  ('Artifactory', 'Cloud & DevOps'),
  ('System Design', 'Architecture'),
  ('Solution Architecture', 'Architecture'),
  ('Enterprise Architecture', 'Architecture'),
  ('Cloud Architecture', 'Architecture'),
  ('API Design', 'Architecture'),
  ('Event-Driven Architecture', 'Architecture'),
  ('Domain-Driven Design', 'Architecture'),
  ('TOGAF', 'Architecture'),
  ('Quality Assurance', 'Testing'),
  ('Manual Testing', 'Testing'),
  ('Test Automation', 'Testing'),
  ('SDET', 'Testing'),
  ('Selenium', 'Testing'),
  ('Cypress', 'Testing'),
  ('Playwright', 'Testing'),
  ('Puppeteer', 'Testing'),
  ('Appium', 'Testing'),
  ('Jest', 'Testing'),
  ('JUnit', 'Testing'),
  ('TestNG', 'Testing'),
  ('Mocha', 'Testing'),
  ('Mockito', 'Testing'),
  ('Cucumber', 'Testing'),
  ('SpecFlow', 'Testing'),
  ('BDD', 'Testing'),
  ('TDD', 'Testing'),
  ('Robot Framework', 'Testing'),
  ('API Testing', 'Testing'),
  ('Performance Testing', 'Testing'),
  ('Load Testing', 'Testing'),
  ('JMeter', 'Testing'),
  ('K6', 'Testing'),
  ('Security Testing', 'Testing'),
  ('Regression Testing', 'Testing'),
  ('UAT', 'Testing'),
  ('Test Planning', 'Testing'),
  ('Test Case Design', 'Testing'),
  ('Bug Tracking', 'Testing'),
  ('Defect Management', 'Testing'),
  ('Linux', 'IT Administration'),
  ('System Administration', 'IT Administration'),
  ('Windows Server', 'IT Administration'),
  ('Linux Administration', 'IT Administration'),
  ('macOS Administration', 'IT Administration'),
  ('Active Directory', 'IT Administration'),
  ('Group Policy', 'IT Administration'),
  ('LDAP', 'IT Administration'),
  ('DNS', 'IT Administration'),
  ('DHCP', 'IT Administration'),
  ('VMware', 'IT Administration'),
  ('Hyper-V', 'IT Administration'),
  ('Virtualization', 'IT Administration'),
  ('Citrix', 'IT Administration'),
  ('Exchange Server', 'IT Administration'),
  ('Microsoft 365', 'IT Administration'),
  ('Office 365 Administration', 'IT Administration'),
  ('Azure AD', 'IT Administration'),
  ('Intune', 'IT Administration'),
  ('SCCM', 'IT Administration'),
  ('Endpoint Management', 'IT Administration'),
  ('Backup and Recovery', 'IT Administration'),
  ('Disaster Recovery', 'IT Administration'),
  ('Patch Management', 'IT Administration'),
  ('PKI', 'IT Administration'),
  ('Certificate Management', 'IT Administration'),
  ('Storage Administration', 'IT Administration'),
  ('SAN', 'IT Administration'),
  ('NAS', 'IT Administration'),
  ('IT Support', 'IT Support'),
  ('Technical Support', 'IT Support'),
  ('Help Desk', 'IT Support'),
  ('Service Desk', 'IT Support'),
  ('Desktop Support', 'IT Support'),
  ('End User Support', 'IT Support'),
  ('Remote Support', 'IT Support'),
  ('Troubleshooting', 'IT Support'),
  ('Hardware Support', 'IT Support'),
  ('Software Installation', 'IT Support'),
  ('ITIL', 'IT Support'),
  ('ITIL Foundation', 'IT Support'),
  ('ITSM', 'IT Support'),
  ('Incident Management', 'IT Support'),
  ('Problem Management', 'IT Support'),
  ('Change Management', 'IT Support'),
  ('Ticketing Systems', 'IT Support'),
  ('Zendesk', 'IT Support'),
  ('Freshdesk', 'IT Support'),
  ('Network Administration', 'Networking'),
  ('Network Engineering', 'Networking'),
  ('Cisco', 'Networking'),
  ('CCNA', 'Networking'),
  ('CCNP', 'Networking'),
  ('TCP/IP', 'Networking'),
  ('Routing and Switching', 'Networking'),
  ('Firewalls', 'Networking'),
  ('Palo Alto', 'Networking'),
  ('Fortinet', 'Networking'),
  ('VPN', 'Networking'),
  ('WAN', 'Networking'),
  ('LAN', 'Networking'),
  ('Wireless Networking', 'Networking'),
  ('SD-WAN', 'Networking'),
  ('Load Balancing', 'Networking'),
  ('Network Security', 'Networking'),
  ('VoIP', 'Networking'),
  ('Cybersecurity', 'Security'),
  ('Information Security', 'Security'),
  ('OAuth', 'Security'),
  ('JWT', 'Security'),
  ('IAM', 'Security'),
  ('SIEM', 'Security'),
  ('SOC', 'Security'),
  ('Penetration Testing', 'Security'),
  ('Vulnerability Assessment', 'Security'),
  ('CompTIA Security+', 'Security'),
  ('CISSP', 'Security'),
  ('CEH', 'Security'),
  ('OWASP', 'Security'),
  ('Zero Trust', 'Security'),
  ('GDPR', 'Security'),
  ('SOC 2', 'Security'),
  ('Risk Assessment', 'Security'),
  ('Security Operations', 'Security'),
  ('Figma', 'Design'),
  ('Adobe XD', 'Design'),
  ('UI Design', 'Design'),
  ('UX Design', 'Design'),
  ('User Research', 'Design'),
  ('Wireframing', 'Design'),
  ('Design Systems', 'Design'),
  ('Prototyping', 'Design'),
  ('Accessibility', 'Design'),
  ('Git', 'Tools'),
  ('Jira', 'Tools'),
  ('Confluence', 'Tools'),
  ('Webpack', 'Tools'),
  ('Vite', 'Tools'),
  ('Storybook', 'Tools'),
  ('Postman', 'Tools'),
  ('VS Code', 'Tools'),
  ('Visual Studio', 'Tools'),
  ('IntelliJ IDEA', 'Tools'),
  ('Eclipse', 'Tools'),
  ('Slack', 'Tools'),
  ('Microsoft Teams', 'Tools'),
  ('SAP', 'Enterprise'),
  ('Salesforce', 'Enterprise'),
  ('ServiceNow', 'Enterprise'),
  ('SharePoint', 'Enterprise'),
  ('Power Platform', 'Enterprise'),
  ('Workday', 'Enterprise'),
  ('Oracle EBS', 'Enterprise'),
  ('NetSuite', 'Enterprise'),
  ('SSIS', 'Enterprise'),
  ('SSRS', 'Enterprise'),
  ('RPA', 'Enterprise'),
  ('UiPath', 'Enterprise'),
  ('Blue Prism', 'Enterprise'),
  ('Product Management', 'Product'),
  ('Product Strategy', 'Product'),
  ('Roadmapping', 'Product'),
  ('Product Owner', 'Product'),
  ('Business Analysis', 'Product'),
  ('Requirements Gathering', 'Product'),
  ('Agile', 'Process'),
  ('Scrum', 'Process'),
  ('Kanban', 'Process'),
  ('SAFe', 'Process'),
  ('Waterfall', 'Process'),
  ('Project Management', 'Process'),
  ('PMP', 'Process'),
  ('Prince2', 'Process'),
  ('Stakeholder Management', 'Soft Skills'),
  ('Technical Writing', 'Soft Skills'),
  ('Leadership', 'Soft Skills'),
  ('Communication', 'Soft Skills'),
  ('Customer Service', 'Soft Skills'),
  ('Problem Solving', 'Soft Skills'),
  ('Team Collaboration', 'Soft Skills'),
  ('Time Management', 'Soft Skills'),
  ('Critical Thinking', 'Soft Skills'),
  ('Mentoring', 'Soft Skills'),
  ('Blockchain', 'Emerging'),
  ('IoT', 'Emerging'),
  ('Edge Computing', 'Emerging'),
  ('AR/VR', 'Emerging')
) AS v(name, category)
WHERE sc.name = v.name AND sc.category IS DISTINCT FROM v.category;
