/** Default IT skills seeded into SkillCatalog on first load. */
export const DEFAULT_SKILL_CATALOG: { name: string; category: string }[] = [
  // Languages
  { name: 'JavaScript', category: 'Languages' },
  { name: 'TypeScript', category: 'Languages' },
  { name: 'Python', category: 'Languages' },
  { name: 'Java', category: 'Languages' },
  { name: 'C#', category: 'Languages' },
  { name: 'C++', category: 'Languages' },
  { name: 'Go', category: 'Languages' },
  { name: 'Rust', category: 'Languages' },
  { name: 'Kotlin', category: 'Languages' },
  { name: 'Swift', category: 'Languages' },
  { name: 'PHP', category: 'Languages' },
  { name: 'Ruby', category: 'Languages' },
  { name: 'Scala', category: 'Languages' },
  { name: 'R', category: 'Languages' },
  { name: 'Perl', category: 'Languages' },
  { name: 'Objective-C', category: 'Languages' },
  { name: 'Dart', category: 'Languages' },
  { name: 'Elixir', category: 'Languages' },
  { name: 'Haskell', category: 'Languages' },
  { name: 'Lua', category: 'Languages' },
  { name: 'Groovy', category: 'Languages' },
  { name: 'Clojure', category: 'Languages' },
  { name: 'Visual Basic', category: 'Languages' },
  { name: 'COBOL', category: 'Languages' },
  { name: 'PowerShell', category: 'Languages' },
  { name: 'Shell Scripting', category: 'Languages' },
  { name: 'Bash', category: 'Languages' },
  { name: 'SQL', category: 'Languages' },
  { name: 'PL/SQL', category: 'Languages' },

  // Frontend
  { name: 'React', category: 'Frontend' },
  { name: 'Next.js', category: 'Frontend' },
  { name: 'Angular', category: 'Frontend' },
  { name: 'Vue.js', category: 'Frontend' },
  { name: 'Svelte', category: 'Frontend' },
  { name: 'SvelteKit', category: 'Frontend' },
  { name: 'Ember.js', category: 'Frontend' },
  { name: 'jQuery', category: 'Frontend' },
  { name: 'HTML', category: 'Frontend' },
  { name: 'CSS', category: 'Frontend' },
  { name: 'Tailwind CSS', category: 'Frontend' },
  { name: 'Bootstrap', category: 'Frontend' },
  { name: 'Material UI', category: 'Frontend' },
  { name: 'SASS', category: 'Frontend' },
  { name: 'Redux', category: 'Frontend' },
  { name: 'Web Components', category: 'Frontend' },
  { name: 'Responsive Design', category: 'Frontend' },

  // Backend
  { name: 'Node.js', category: 'Backend' },
  { name: 'Express', category: 'Backend' },
  { name: 'NestJS', category: 'Backend' },
  { name: 'Django', category: 'Backend' },
  { name: 'Flask', category: 'Backend' },
  { name: 'FastAPI', category: 'Backend' },
  { name: 'Spring Boot', category: 'Backend' },
  { name: '.NET', category: 'Backend' },
  { name: 'ASP.NET Core', category: 'Backend' },
  { name: 'Laravel', category: 'Backend' },
  { name: 'Ruby on Rails', category: 'Backend' },
  { name: 'GraphQL', category: 'Backend' },
  { name: 'REST APIs', category: 'Backend' },
  { name: 'gRPC', category: 'Backend' },
  { name: 'Microservices', category: 'Backend' },
  { name: 'Serverless', category: 'Backend' },
  { name: 'API Development', category: 'Backend' },
  { name: 'Full Stack Development', category: 'Backend' },
  { name: 'Prisma', category: 'Backend' },
  { name: 'Supabase', category: 'Backend' },
  { name: 'Firebase', category: 'Backend' },

  // Mobile
  { name: 'React Native', category: 'Mobile' },
  { name: 'Flutter', category: 'Mobile' },
  { name: 'Android', category: 'Mobile' },
  { name: 'iOS', category: 'Mobile' },
  { name: 'SwiftUI', category: 'Mobile' },
  { name: 'Xamarin', category: 'Mobile' },
  { name: 'Mobile Development', category: 'Mobile' },

  // Data
  { name: 'PostgreSQL', category: 'Data' },
  { name: 'MySQL', category: 'Data' },
  { name: 'MariaDB', category: 'Data' },
  { name: 'MongoDB', category: 'Data' },
  { name: 'Redis', category: 'Data' },
  { name: 'Elasticsearch', category: 'Data' },
  { name: 'DynamoDB', category: 'Data' },
  { name: 'Cassandra', category: 'Data' },
  { name: 'Oracle Database', category: 'Data' },
  { name: 'SQL Server', category: 'Data' },
  { name: 'Neo4j', category: 'Data' },
  { name: 'Snowflake', category: 'Data' },
  { name: 'dbt', category: 'Data' },
  { name: 'Apache Spark', category: 'Data' },
  { name: 'Hadoop', category: 'Data' },
  { name: 'Kafka', category: 'Data' },
  { name: 'Apache Airflow', category: 'Data' },
  { name: 'ETL', category: 'Data' },
  { name: 'Data Analysis', category: 'Data' },
  { name: 'Data Engineering', category: 'Data' },
  { name: 'Data Warehousing', category: 'Data' },
  { name: 'Database Administration', category: 'Data' },

  // Data Science
  { name: 'Machine Learning', category: 'Data Science' },
  { name: 'Deep Learning', category: 'Data Science' },
  { name: 'TensorFlow', category: 'Data Science' },
  { name: 'PyTorch', category: 'Data Science' },
  { name: 'Scikit-learn', category: 'Data Science' },
  { name: 'Pandas', category: 'Data Science' },
  { name: 'NumPy', category: 'Data Science' },
  { name: 'NLP', category: 'Data Science' },
  { name: 'Computer Vision', category: 'Data Science' },
  { name: 'Generative AI', category: 'Data Science' },
  { name: 'LLMs', category: 'Data Science' },
  { name: 'MLOps', category: 'Data Science' },

  // Analytics
  { name: 'Tableau', category: 'Analytics' },
  { name: 'Power BI', category: 'Analytics' },
  { name: 'Looker', category: 'Analytics' },
  { name: 'Excel', category: 'Analytics' },
  { name: 'Google Analytics', category: 'Analytics' },
  { name: 'Business Intelligence', category: 'Analytics' },

  // Cloud & DevOps
  { name: 'AWS', category: 'Cloud & DevOps' },
  { name: 'Azure', category: 'Cloud & DevOps' },
  { name: 'Google Cloud', category: 'Cloud & DevOps' },
  { name: 'Docker', category: 'Cloud & DevOps' },
  { name: 'Kubernetes', category: 'Cloud & DevOps' },
  { name: 'Terraform', category: 'Cloud & DevOps' },
  { name: 'Ansible', category: 'Cloud & DevOps' },
  { name: 'Puppet', category: 'Cloud & DevOps' },
  { name: 'Chef', category: 'Cloud & DevOps' },
  { name: 'CI/CD', category: 'Cloud & DevOps' },
  { name: 'Jenkins', category: 'Cloud & DevOps' },
  { name: 'GitHub Actions', category: 'Cloud & DevOps' },
  { name: 'GitLab CI', category: 'Cloud & DevOps' },
  { name: 'CircleCI', category: 'Cloud & DevOps' },
  { name: 'Azure DevOps', category: 'Cloud & DevOps' },
  { name: 'ArgoCD', category: 'Cloud & DevOps' },
  { name: 'GitOps', category: 'Cloud & DevOps' },
  { name: 'Apache', category: 'Cloud & DevOps' },
  { name: 'Nginx', category: 'Cloud & DevOps' },
  { name: 'Helm', category: 'Cloud & DevOps' },
  { name: 'Prometheus', category: 'Cloud & DevOps' },
  { name: 'Grafana', category: 'Cloud & DevOps' },
  { name: 'ELK Stack', category: 'Cloud & DevOps' },
  { name: 'Splunk', category: 'Cloud & DevOps' },
  { name: 'Datadog', category: 'Cloud & DevOps' },
  { name: 'New Relic', category: 'Cloud & DevOps' },
  { name: 'Nagios', category: 'Cloud & DevOps' },
  { name: 'Zabbix', category: 'Cloud & DevOps' },
  { name: 'Vagrant', category: 'Cloud & DevOps' },
  { name: 'Packer', category: 'Cloud & DevOps' },
  { name: 'CloudFormation', category: 'Cloud & DevOps' },
  { name: 'Pulumi', category: 'Cloud & DevOps' },
  { name: 'Nomad', category: 'Cloud & DevOps' },
  { name: 'Istio', category: 'Cloud & DevOps' },
  { name: 'OpenShift', category: 'Cloud & DevOps' },
  { name: 'AWS Lambda', category: 'Cloud & DevOps' },
  { name: 'Infrastructure as Code', category: 'Cloud & DevOps' },
  { name: 'Site Reliability Engineering', category: 'Cloud & DevOps' },
  { name: 'DevOps', category: 'Cloud & DevOps' },
  { name: 'Release Management', category: 'Cloud & DevOps' },
  { name: 'SonarQube', category: 'Cloud & DevOps' },
  { name: 'Nexus', category: 'Cloud & DevOps' },
  { name: 'Artifactory', category: 'Cloud & DevOps' },

  // Architecture
  { name: 'System Design', category: 'Architecture' },
  { name: 'Solution Architecture', category: 'Architecture' },
  { name: 'Enterprise Architecture', category: 'Architecture' },
  { name: 'Cloud Architecture', category: 'Architecture' },
  { name: 'API Design', category: 'Architecture' },
  { name: 'Event-Driven Architecture', category: 'Architecture' },
  { name: 'Domain-Driven Design', category: 'Architecture' },
  { name: 'TOGAF', category: 'Architecture' },

  // Testing
  { name: 'Quality Assurance', category: 'Testing' },
  { name: 'Manual Testing', category: 'Testing' },
  { name: 'Test Automation', category: 'Testing' },
  { name: 'SDET', category: 'Testing' },
  { name: 'Selenium', category: 'Testing' },
  { name: 'Cypress', category: 'Testing' },
  { name: 'Playwright', category: 'Testing' },
  { name: 'Puppeteer', category: 'Testing' },
  { name: 'Appium', category: 'Testing' },
  { name: 'Jest', category: 'Testing' },
  { name: 'JUnit', category: 'Testing' },
  { name: 'TestNG', category: 'Testing' },
  { name: 'Mocha', category: 'Testing' },
  { name: 'Mockito', category: 'Testing' },
  { name: 'Cucumber', category: 'Testing' },
  { name: 'SpecFlow', category: 'Testing' },
  { name: 'BDD', category: 'Testing' },
  { name: 'TDD', category: 'Testing' },
  { name: 'Robot Framework', category: 'Testing' },
  { name: 'API Testing', category: 'Testing' },
  { name: 'Performance Testing', category: 'Testing' },
  { name: 'Load Testing', category: 'Testing' },
  { name: 'JMeter', category: 'Testing' },
  { name: 'K6', category: 'Testing' },
  { name: 'Security Testing', category: 'Testing' },
  { name: 'Regression Testing', category: 'Testing' },
  { name: 'UAT', category: 'Testing' },
  { name: 'Test Planning', category: 'Testing' },
  { name: 'Test Case Design', category: 'Testing' },
  { name: 'Bug Tracking', category: 'Testing' },
  { name: 'Defect Management', category: 'Testing' },

  // IT Administration
  { name: 'Linux', category: 'IT Administration' },
  { name: 'System Administration', category: 'IT Administration' },
  { name: 'Windows Server', category: 'IT Administration' },
  { name: 'Linux Administration', category: 'IT Administration' },
  { name: 'macOS Administration', category: 'IT Administration' },
  { name: 'Active Directory', category: 'IT Administration' },
  { name: 'Group Policy', category: 'IT Administration' },
  { name: 'LDAP', category: 'IT Administration' },
  { name: 'DNS', category: 'IT Administration' },
  { name: 'DHCP', category: 'IT Administration' },
  { name: 'VMware', category: 'IT Administration' },
  { name: 'Hyper-V', category: 'IT Administration' },
  { name: 'Virtualization', category: 'IT Administration' },
  { name: 'Citrix', category: 'IT Administration' },
  { name: 'Exchange Server', category: 'IT Administration' },
  { name: 'Microsoft 365', category: 'IT Administration' },
  { name: 'Office 365 Administration', category: 'IT Administration' },
  { name: 'Azure AD', category: 'IT Administration' },
  { name: 'Intune', category: 'IT Administration' },
  { name: 'SCCM', category: 'IT Administration' },
  { name: 'Endpoint Management', category: 'IT Administration' },
  { name: 'Backup and Recovery', category: 'IT Administration' },
  { name: 'Disaster Recovery', category: 'IT Administration' },
  { name: 'Patch Management', category: 'IT Administration' },
  { name: 'PKI', category: 'IT Administration' },
  { name: 'Certificate Management', category: 'IT Administration' },
  { name: 'Storage Administration', category: 'IT Administration' },
  { name: 'SAN', category: 'IT Administration' },
  { name: 'NAS', category: 'IT Administration' },

  // IT Support
  { name: 'IT Support', category: 'IT Support' },
  { name: 'Technical Support', category: 'IT Support' },
  { name: 'Help Desk', category: 'IT Support' },
  { name: 'Service Desk', category: 'IT Support' },
  { name: 'Desktop Support', category: 'IT Support' },
  { name: 'End User Support', category: 'IT Support' },
  { name: 'Remote Support', category: 'IT Support' },
  { name: 'Troubleshooting', category: 'IT Support' },
  { name: 'Hardware Support', category: 'IT Support' },
  { name: 'Software Installation', category: 'IT Support' },
  { name: 'ITIL', category: 'IT Support' },
  { name: 'ITIL Foundation', category: 'IT Support' },
  { name: 'ITSM', category: 'IT Support' },
  { name: 'Incident Management', category: 'IT Support' },
  { name: 'Problem Management', category: 'IT Support' },
  { name: 'Change Management', category: 'IT Support' },
  { name: 'Ticketing Systems', category: 'IT Support' },
  { name: 'Zendesk', category: 'IT Support' },
  { name: 'Freshdesk', category: 'IT Support' },

  // Networking
  { name: 'Network Administration', category: 'Networking' },
  { name: 'Network Engineering', category: 'Networking' },
  { name: 'Cisco', category: 'Networking' },
  { name: 'CCNA', category: 'Networking' },
  { name: 'CCNP', category: 'Networking' },
  { name: 'TCP/IP', category: 'Networking' },
  { name: 'Routing and Switching', category: 'Networking' },
  { name: 'Firewalls', category: 'Networking' },
  { name: 'Palo Alto', category: 'Networking' },
  { name: 'Fortinet', category: 'Networking' },
  { name: 'VPN', category: 'Networking' },
  { name: 'WAN', category: 'Networking' },
  { name: 'LAN', category: 'Networking' },
  { name: 'Wireless Networking', category: 'Networking' },
  { name: 'SD-WAN', category: 'Networking' },
  { name: 'Load Balancing', category: 'Networking' },
  { name: 'Network Security', category: 'Networking' },
  { name: 'VoIP', category: 'Networking' },

  // Security
  { name: 'Cybersecurity', category: 'Security' },
  { name: 'Information Security', category: 'Security' },
  { name: 'OAuth', category: 'Security' },
  { name: 'JWT', category: 'Security' },
  { name: 'IAM', category: 'Security' },
  { name: 'SIEM', category: 'Security' },
  { name: 'SOC', category: 'Security' },
  { name: 'Penetration Testing', category: 'Security' },
  { name: 'Vulnerability Assessment', category: 'Security' },
  { name: 'CompTIA Security+', category: 'Security' },
  { name: 'CISSP', category: 'Security' },
  { name: 'CEH', category: 'Security' },
  { name: 'OWASP', category: 'Security' },
  { name: 'Zero Trust', category: 'Security' },
  { name: 'GDPR', category: 'Security' },
  { name: 'SOC 2', category: 'Security' },
  { name: 'Risk Assessment', category: 'Security' },
  { name: 'Security Operations', category: 'Security' },

  // Design
  { name: 'Figma', category: 'Design' },
  { name: 'Adobe XD', category: 'Design' },
  { name: 'UI Design', category: 'Design' },
  { name: 'UX Design', category: 'Design' },
  { name: 'User Research', category: 'Design' },
  { name: 'Wireframing', category: 'Design' },
  { name: 'Design Systems', category: 'Design' },
  { name: 'Prototyping', category: 'Design' },
  { name: 'Accessibility', category: 'Design' },

  // Tools
  { name: 'Git', category: 'Tools' },
  { name: 'Jira', category: 'Tools' },
  { name: 'Confluence', category: 'Tools' },
  { name: 'Webpack', category: 'Tools' },
  { name: 'Vite', category: 'Tools' },
  { name: 'Storybook', category: 'Tools' },
  { name: 'Postman', category: 'Tools' },
  { name: 'VS Code', category: 'Tools' },
  { name: 'Visual Studio', category: 'Tools' },
  { name: 'IntelliJ IDEA', category: 'Tools' },
  { name: 'Eclipse', category: 'Tools' },
  { name: 'Slack', category: 'Tools' },
  { name: 'Microsoft Teams', category: 'Tools' },

  // Enterprise
  { name: 'SAP', category: 'Enterprise' },
  { name: 'Salesforce', category: 'Enterprise' },
  { name: 'ServiceNow', category: 'Enterprise' },
  { name: 'SharePoint', category: 'Enterprise' },
  { name: 'Power Platform', category: 'Enterprise' },
  { name: 'Workday', category: 'Enterprise' },
  { name: 'Oracle EBS', category: 'Enterprise' },
  { name: 'NetSuite', category: 'Enterprise' },
  { name: 'SSIS', category: 'Enterprise' },
  { name: 'SSRS', category: 'Enterprise' },
  { name: 'RPA', category: 'Enterprise' },
  { name: 'UiPath', category: 'Enterprise' },
  { name: 'Blue Prism', category: 'Enterprise' },

  // Product
  { name: 'Product Management', category: 'Product' },
  { name: 'Product Strategy', category: 'Product' },
  { name: 'Roadmapping', category: 'Product' },
  { name: 'Product Owner', category: 'Product' },
  { name: 'Business Analysis', category: 'Product' },
  { name: 'Requirements Gathering', category: 'Product' },

  // Process
  { name: 'Agile', category: 'Process' },
  { name: 'Scrum', category: 'Process' },
  { name: 'Kanban', category: 'Process' },
  { name: 'SAFe', category: 'Process' },
  { name: 'Waterfall', category: 'Process' },
  { name: 'Project Management', category: 'Process' },
  { name: 'PMP', category: 'Process' },
  { name: 'Prince2', category: 'Process' },

  // Soft Skills
  { name: 'Stakeholder Management', category: 'Soft Skills' },
  { name: 'Technical Writing', category: 'Soft Skills' },
  { name: 'Leadership', category: 'Soft Skills' },
  { name: 'Communication', category: 'Soft Skills' },
  { name: 'Customer Service', category: 'Soft Skills' },
  { name: 'Problem Solving', category: 'Soft Skills' },
  { name: 'Team Collaboration', category: 'Soft Skills' },
  { name: 'Time Management', category: 'Soft Skills' },
  { name: 'Critical Thinking', category: 'Soft Skills' },
  { name: 'Mentoring', category: 'Soft Skills' },

  // Emerging
  { name: 'Blockchain', category: 'Emerging' },
  { name: 'IoT', category: 'Emerging' },
  { name: 'Edge Computing', category: 'Emerging' },
  { name: 'AR/VR', category: 'Emerging' },
]
