/** Demo dataset for `npm run db:seed-demo`. Demo emails use @Stitch.com — safe to delete/re-seed. */

import { DEV_PASSWORD, devUserName } from './devUsers.js'

export const DEMO_VENDOR_CODE = 'DEMO-STAFFING'

export const DEMO_RESUME_URLS = [
  'https://www.africau.edu/images/default/sample.pdf',
  'https://pdfobject.com/pdf/sample.pdf',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  'https://www.orimi.com/pdf-test.pdf',
] as const

export const DEMO_PORTAL_USERS = [
  {
    email: 'aisha.mehta@Stitch.com',
    name: 'Aisha Mehta',
    password: DEV_PASSWORD,
    applyToJobCode: 'REQ28062026001',
  },
  {
    email: 'rohan.kapoor@Stitch.com',
    name: 'Rohan Kapoor',
    password: DEV_PASSWORD,
    applyToJobCode: 'REQ28062026002',
  },
  {
    email: 'neha.iyer@Stitch.com',
    name: 'Neha Iyer',
    password: DEV_PASSWORD,
    applyToJobCode: 'REQ28062026003',
  },
  {
    email: 'vikram.desai@Stitch.com',
    name: 'Vikram Desai',
    password: DEV_PASSWORD,
    applyToJobCode: 'REQ28062026004',
  },
  {
    email: 'priya.nair@Stitch.com',
    name: 'Priya Nair',
    password: DEV_PASSWORD,
    applyToJobCode: 'REQ28062026005',
  },
  /** Logged-in candidate account with no application yet (portal shows “apply to get started”). */
  {
    email: 'karan.joshi@Stitch.com',
    name: 'Karan Joshi',
    password: DEV_PASSWORD,
    applyToJobCode: null,
  },
  {
    email: 'meera.shah@Stitch.com',
    name: 'Meera Shah',
    password: DEV_PASSWORD,
    applyToJobCode: null,
  },
] as const

export const DEMO_REQUIREMENTS = [
  {
    jobCode: 'REQ28062026001',
    title: 'Senior Software Engineer',
    department: 'Engineering',
    hiringManager: devUserName('HIRING_MANAGER'),
    client: 'Acme Corp',
    location: 'Bangalore (Hybrid)',
    priority: 'HIGH',
    openings: 3,
    filled: 0,
    status: 'LIVE' as const,
    visibleToCandidates: true,
    visibleToVendors: true,
    primarySkills: ['TypeScript', 'React', 'Node.js', 'PostgreSQL', 'REST APIs'],
    secondarySkills: ['AWS', 'Docker', 'CI/CD', 'System Design'],
    description: 'Build and scale our hiring platform frontend and API.',
    jobDescription:
      'We need a senior engineer with strong TypeScript, React, and Node.js experience. PostgreSQL and REST API design required. AWS and Docker are nice to have.',
  },
  {
    jobCode: 'REQ28062026002',
    title: 'Product Manager',
    department: 'Product',
    hiringManager: devUserName('HR_HEAD'),
    client: 'Acme Corp',
    location: 'Mumbai (Remote)',
    priority: 'MEDIUM',
    openings: 1,
    filled: 0,
    status: 'LIVE' as const,
    visibleToCandidates: true,
    visibleToVendors: false,
    primarySkills: ['Product Strategy', 'Roadmapping', 'Stakeholder Management', 'Agile'],
    secondarySkills: ['SQL', 'Analytics', 'B2B SaaS'],
    description: 'Own the ATS product roadmap and delivery.',
    jobDescription:
      'Product manager with B2B SaaS background, agile delivery, and strong stakeholder communication.',
  },
  {
    jobCode: 'REQ28062026003',
    title: 'DevOps Engineer',
    department: 'Platform',
    hiringManager: devUserName('TEAM_LEAD'),
    client: 'Internal',
    location: 'Hyderabad',
    priority: 'HIGH',
    openings: 2,
    filled: 0,
    status: 'LIVE' as const,
    visibleToCandidates: true,
    visibleToVendors: true,
    primarySkills: ['Kubernetes', 'Terraform', 'AWS', 'CI/CD', 'Linux'],
    secondarySkills: ['Prometheus', 'Grafana', 'Helm'],
    description: 'Run production infrastructure for the ATS stack.',
    jobDescription:
      'DevOps engineer skilled in Kubernetes, Terraform, AWS, and CI/CD pipelines on Linux.',
  },
  {
    jobCode: 'REQ28062026004',
    title: 'UX Designer',
    department: 'Design',
    hiringManager: devUserName('HIRING_MANAGER'),
    client: 'Acme Corp',
    location: 'Remote',
    priority: 'LOW',
    openings: 2,
    filled: 0,
    status: 'LIVE' as const,
    visibleToCandidates: true,
    visibleToVendors: false,
    primarySkills: ['Figma', 'User Research', 'Wireframing', 'Design Systems'],
    secondarySkills: ['HTML', 'CSS', 'Accessibility'],
    description: 'Design recruiter and candidate experiences.',
    jobDescription:
      'UX designer with Figma, user research, wireframing, and design system experience.',
  },
  {
    jobCode: 'REQ28062026005',
    title: 'Data Analyst',
    department: 'Analytics',
    hiringManager: devUserName('HR_MANAGER'),
    client: 'Internal',
    location: 'Chennai',
    priority: 'MEDIUM',
    openings: 2,
    filled: 0,
    status: 'LIVE' as const,
    visibleToCandidates: true,
    visibleToVendors: true,
    primarySkills: ['SQL', 'Python', 'Tableau', 'Excel'],
    secondarySkills: ['dbt', 'Snowflake', 'Statistics'],
    description: 'Hiring funnel analytics and reporting.',
    jobDescription:
      'Data analyst with SQL, Python, Tableau, and strong Excel skills for recruiting metrics.',
  },
  {
    jobCode: 'REQ28062026006',
    title: 'HR Coordinator',
    department: 'HR',
    hiringManager: devUserName('HR_HEAD'),
    client: 'Internal',
    location: 'Delhi NCR',
    priority: 'LOW',
    openings: 1,
    filled: 0,
    status: 'PENDING_APPROVAL' as const,
    visibleToCandidates: false,
    visibleToVendors: false,
    primarySkills: ['Onboarding', 'HR Operations', 'Communication'],
    secondarySkills: ['ATS', 'Compliance'],
    description: 'Coordinate interviews and offers.',
    jobDescription: 'HR coordinator for interview scheduling and offer coordination.',
  },
  {
    jobCode: 'REQ28062026007',
    title: 'SDET / QA Automation Engineer',
    department: 'Engineering',
    hiringManager: devUserName('HIRING_MANAGER'),
    client: 'Acme Corp',
    location: 'Bangalore (Hybrid)',
    priority: 'MEDIUM',
    openings: 2,
    filled: 0,
    status: 'LIVE' as const,
    visibleToCandidates: true,
    visibleToVendors: true,
    primarySkills: ['Selenium', 'Cypress', 'API Testing', 'Java', 'CI/CD'],
    secondarySkills: ['Playwright', 'Jest', 'Postman'],
    description: 'Automate regression and API test suites for the hiring platform.',
    jobDescription:
      'SDET with strong automation experience in Selenium or Cypress, API testing, and CI integration. Java or TypeScript test stacks preferred.',
  },
  {
    jobCode: 'REQ28062026008',
    title: 'Senior Java Backend Engineer',
    department: 'Engineering',
    hiringManager: devUserName('TEAM_LEAD'),
    client: 'FinServe Ltd',
    location: 'Pune',
    priority: 'HIGH',
    openings: 2,
    filled: 0,
    status: 'LIVE' as const,
    visibleToCandidates: true,
    visibleToVendors: true,
    primarySkills: ['Java', 'Spring Boot', 'Microservices', 'PostgreSQL', 'Kafka'],
    secondarySkills: ['AWS', 'Redis', 'JUnit'],
    description: 'Build high-throughput services for payments and lending workflows.',
    jobDescription:
      'Senior Java engineer with Spring Boot, microservices, PostgreSQL, and event-driven architecture using Kafka.',
  },
] as const

export type DemoCandidateSeed = {
  email: string
  name: string
  role: string
  status: string
  source: string
  jobCode?: string | null
  phone?: string
  location?: string
  totalExperience?: string
  currentCompany?: string
  primarySkills?: string[]
  secondarySkills?: string[]
  resumeSnippet: string
  vendorSubmitted?: boolean
  interviewProgress?: 'l1-scheduled' | 'l1-done-l2-scheduled' | 'all-rounds-complete'
  offerStatus?: 'PENDING' | 'SENT' | 'ACCEPTED'
}

export const DEMO_CANDIDATES: DemoCandidateSeed[] = [
  {
    email: 'arjun.pillai@Stitch.com',
    name: 'Arjun Pillai',
    role: 'Full Stack Developer',
    status: 'SCREENING',
    source: 'LinkedIn',
    jobCode: 'REQ28062026001',
    location: 'Bangalore',
    totalExperience: '6 Years',
    currentCompany: 'TechNova',
    primarySkills: ['TypeScript', 'React', 'Node.js', 'PostgreSQL'],
    secondarySkills: ['AWS', 'Docker'],
    resumeSnippet:
      'Arjun Pillai — Full Stack Developer with 6 years experience. Skills: TypeScript, React, Node.js, PostgreSQL, REST APIs, AWS, Docker.',
  },
  {
    email: 'sneha.reddy@Stitch.com',
    name: 'Sneha Reddy',
    role: 'Backend Engineer',
    status: 'SHORTLISTED',
    source: 'Referral',
    jobCode: 'REQ28062026001',
    location: 'Hyderabad',
    totalExperience: '8 Years',
    currentCompany: 'CloudBase',
    primarySkills: ['Node.js', 'TypeScript', 'PostgreSQL', 'System Design'],
    secondarySkills: ['Kubernetes', 'Redis'],
    resumeSnippet:
      'Sneha Reddy — Backend engineer, 8 years. Node.js, TypeScript, PostgreSQL, REST APIs, system design, Kubernetes.',
  },
  // —— Senior SWE pipeline: one realistic profile per kanban stage ——
  {
    email: 'kavitha.narasimhan@Stitch.com',
    name: 'Kavitha Narasimhan',
    role: 'Senior Software Engineer',
    status: 'SOURCED',
    source: 'LinkedIn Recruiter',
    jobCode: 'REQ28062026001',
    phone: '+91 98450 11223',
    location: 'Bangalore',
    totalExperience: '7 Years',
    currentCompany: 'Infosys',
    primarySkills: ['TypeScript', 'React', 'Node.js', 'PostgreSQL'],
    secondarySkills: ['AWS', 'GraphQL'],
    resumeSnippet:
      'Kavitha Narasimhan — Senior engineer at Infosys, 7 years building React/Node products. Led migration to TypeScript microservices on AWS.',
  },
  {
    email: 'priyanka.sharma@Stitch.com',
    name: 'Priyanka Sharma',
    role: 'Senior Software Engineer',
    status: 'OFFER',
    source: 'Employee Referral',
    jobCode: 'REQ28062026001',
    phone: '+91 99887 65432',
    location: 'Hyderabad',
    totalExperience: '9 Years',
    currentCompany: 'Flipkart',
    primarySkills: ['TypeScript', 'React', 'Node.js', 'System Design'],
    secondarySkills: ['Kubernetes', 'PostgreSQL'],
    resumeSnippet:
      'Priyanka Sharma — Staff-level IC at Flipkart, 9 years. TypeScript, React, Node.js, system design, PostgreSQL, Kubernetes.',
    interviewProgress: 'all-rounds-complete',
    offerStatus: 'SENT',
  },
  {
    email: 'vikram.singh@Stitch.com',
    name: 'Vikram Singh',
    role: 'Senior Software Engineer',
    status: 'HIRED',
    source: 'Recruiter Added',
    jobCode: 'REQ28062026001',
    phone: '+91 98765 44321',
    location: 'Gurgaon',
    totalExperience: '8 Years',
    currentCompany: 'Razorpay',
    primarySkills: ['TypeScript', 'React', 'Node.js', 'REST APIs'],
    secondarySkills: ['Docker', 'CI/CD'],
    resumeSnippet:
      'Vikram Singh — Razorpay, 8 years full-stack. TypeScript, React, Node.js, payment APIs, Docker, CI/CD pipelines.',
    interviewProgress: 'all-rounds-complete',
    offerStatus: 'ACCEPTED',
  },
  {
    email: 'divya.menon@Stitch.com',
    name: 'Divya Menon',
    role: 'Senior Software Engineer',
    status: 'JOINED',
    source: 'Vendor: Demo Staffing Co',
    jobCode: 'REQ28062026001',
    phone: '+91 91234 55678',
    location: 'Bangalore',
    totalExperience: '6 Years',
    currentCompany: 'Formerly Freshworks',
    primarySkills: ['TypeScript', 'React', 'Node.js', 'PostgreSQL'],
    secondarySkills: ['AWS', 'Redis'],
    resumeSnippet:
      'Divya Menon — Ex-Freshworks engineer, 6 years SaaS product development. TypeScript, React, Node.js, PostgreSQL, AWS.',
    vendorSubmitted: true,
    interviewProgress: 'all-rounds-complete',
    offerStatus: 'ACCEPTED',
  },
  {
    email: 'rahul.verma@Stitch.com',
    name: 'Rahul Verma',
    role: 'Software Engineer',
    status: 'REJECTED',
    source: 'Direct Application',
    jobCode: 'REQ28062026001',
    phone: '+91 90123 44556',
    location: 'Noida',
    totalExperience: '3 Years',
    currentCompany: 'Wipro',
    primarySkills: ['Java', 'Spring'],
    secondarySkills: ['SQL'],
    resumeSnippet:
      'Rahul Verma — Wipro, 3 years Java/Spring. Limited frontend and Node.js exposure.',
  },
  {
    email: 'manish.khanna@Stitch.com',
    name: 'Manish Khanna',
    role: 'Software Engineer',
    status: 'INTERVIEW',
    source: 'Recruiter Added',
    jobCode: 'REQ28062026001',
    location: 'Bangalore',
    totalExperience: '5 Years',
    currentCompany: 'CRED',
    primarySkills: ['React', 'TypeScript', 'Node.js'],
    secondarySkills: ['GraphQL', 'Jest'],
    resumeSnippet:
      'Manish Khanna — Software engineer at CRED, 5 years. React, TypeScript, Node.js, PostgreSQL, CI/CD experience.',
    interviewProgress: 'l1-done-l2-scheduled',
  },
  // —— DevOps pipeline coverage ——
  {
    email: 'aditya.kulkarni@Stitch.com',
    name: 'Aditya Kulkarni',
    role: 'DevOps Engineer',
    status: 'SHORTLISTED',
    source: 'LinkedIn',
    jobCode: 'REQ28062026003',
    location: 'Mumbai',
    totalExperience: '5 Years',
    currentCompany: 'TCS Digital',
    primarySkills: ['Kubernetes', 'Terraform', 'AWS'],
    secondarySkills: ['Helm', 'Argo CD'],
    resumeSnippet:
      'Aditya Kulkarni — TCS Digital, 5 years platform engineering. Kubernetes, Terraform, AWS, GitOps with Argo CD.',
  },
  {
    email: 'meera.iyer@Stitch.com',
    name: 'Meera Iyer',
    role: 'Site Reliability Engineer',
    status: 'INTERVIEW',
    source: 'Referral',
    jobCode: 'REQ28062026003',
    location: 'Bangalore',
    totalExperience: '7 Years',
    currentCompany: 'Swiggy',
    primarySkills: ['Kubernetes', 'AWS', 'Prometheus', 'Linux'],
    secondarySkills: ['Python', 'Grafana'],
    resumeSnippet:
      'Meera Iyer — Swiggy SRE, 7 years. Kubernetes, AWS, observability with Prometheus/Grafana, incident response.',
    interviewProgress: 'l1-scheduled',
  },
  {
    email: 'sanjay.patel@Stitch.com',
    name: 'Sanjay Patel',
    role: 'DevOps Engineer',
    status: 'OFFER',
    source: 'Recruiter Added',
    jobCode: 'REQ28062026003',
    location: 'Ahmedabad',
    totalExperience: '6 Years',
    currentCompany: 'Zomato',
    primarySkills: ['AWS', 'Terraform', 'CI/CD', 'Linux'],
    secondarySkills: ['Docker', 'Kubernetes'],
    resumeSnippet:
      'Sanjay Patel — Zomato, 6 years DevOps. AWS, Terraform, Docker, Kubernetes, Jenkins CI/CD.',
    interviewProgress: 'all-rounds-complete',
    offerStatus: 'SENT',
  },
  {
    email: 'lakshmi.rao@Stitch.com',
    name: 'Lakshmi Rao',
    role: 'Platform Engineer',
    status: 'HIRED',
    source: 'Vendor: Demo Staffing Co',
    jobCode: 'REQ28062026003',
    location: 'Hyderabad',
    totalExperience: '8 Years',
    currentCompany: 'Microsoft India',
    primarySkills: ['Azure', 'Kubernetes', 'Terraform'],
    secondarySkills: ['PowerShell', 'GitHub Actions'],
    resumeSnippet:
      'Lakshmi Rao — Microsoft India, 8 years cloud platform. Azure, Kubernetes, Terraform, GitHub Actions.',
    vendorSubmitted: true,
    interviewProgress: 'all-rounds-complete',
    offerStatus: 'ACCEPTED',
  },
  {
    email: 'harish.naidu@Stitch.com',
    name: 'Harish Naidu',
    role: 'DevOps Engineer',
    status: 'JOINED',
    source: 'Employee Referral',
    jobCode: 'REQ28062026003',
    location: 'Chennai',
    totalExperience: '5 Years',
    currentCompany: 'Formerly Paytm',
    primarySkills: ['AWS', 'Kubernetes', 'CI/CD'],
    secondarySkills: ['Ansible', 'Linux'],
    resumeSnippet:
      'Harish Naidu — Ex-Paytm, 5 years DevOps. AWS, Kubernetes, Ansible, Linux, CI/CD automation.',
    interviewProgress: 'all-rounds-complete',
    offerStatus: 'ACCEPTED',
  },
  {
    email: 'nitin.gupta@Stitch.com',
    name: 'Nitin Gupta',
    role: 'Systems Administrator',
    status: 'REJECTED',
    source: 'Vendor: Demo Staffing Co',
    jobCode: 'REQ28062026003',
    location: 'Jaipur',
    totalExperience: '4 Years',
    currentCompany: 'Local IT Services',
    primarySkills: ['Linux', 'Bash'],
    secondarySkills: ['VMware'],
    resumeSnippet:
      'Nitin Gupta — Sysadmin background, limited cloud-native and Kubernetes experience.',
    vendorSubmitted: true,
  },
  // —— QA & Java roles ——
  {
    email: 'shruti.desai@Stitch.com',
    name: 'Shruti Desai',
    role: 'SDET',
    status: 'APPLIED',
    source: 'Candidate Portal',
    jobCode: 'REQ28062026007',
    location: 'Pune',
    totalExperience: '4 Years',
    currentCompany: 'Mindtree',
    primarySkills: ['Selenium', 'Java', 'API Testing'],
    secondarySkills: ['Cypress', 'Postman'],
    resumeSnippet:
      'Shruti Desai — Mindtree SDET, 4 years. Selenium, Java, REST API automation, Cypress, Postman.',
  },
  {
    email: 'anil.reddy@Stitch.com',
    name: 'Anil Reddy',
    role: 'Java Backend Engineer',
    status: 'SCREENING',
    source: 'LinkedIn',
    jobCode: 'REQ28062026008',
    location: 'Hyderabad',
    totalExperience: '6 Years',
    currentCompany: 'HDFC Bank Tech',
    primarySkills: ['Java', 'Spring Boot', 'Microservices', 'PostgreSQL'],
    secondarySkills: ['Kafka', 'Redis'],
    resumeSnippet:
      'Anil Reddy — HDFC Bank, 6 years Java microservices. Spring Boot, PostgreSQL, Kafka event streaming.',
  },
  {
    email: 'fatima.ansari@Stitch.com',
    name: 'Fatima Ansari',
    role: 'Product Manager',
    status: 'OFFER',
    source: 'LinkedIn',
    jobCode: 'REQ28062026002',
    location: 'Mumbai',
    totalExperience: '7 Years',
    currentCompany: 'Nykaa',
    primarySkills: ['Product Strategy', 'Roadmapping', 'Agile', 'B2B SaaS'],
    secondarySkills: ['SQL', 'Analytics'],
    resumeSnippet:
      'Fatima Ansari — Product Manager, 7 years B2B SaaS at Nykaa, agile, roadmapping, stakeholder management, SQL analytics.',
    interviewProgress: 'all-rounds-complete',
    offerStatus: 'SENT',
  },
  {
    email: 'rohan.jadhav@Stitch.com',
    name: 'Rohan Jadhav',
    role: 'Platform Engineer',
    status: 'SOURCED',
    source: 'Vendor: Demo Staffing Co',
    jobCode: 'REQ28062026003',
    location: 'Pune',
    totalExperience: '4 Years',
    currentCompany: 'Persistent Systems',
    primarySkills: ['AWS', 'Terraform', 'Linux', 'CI/CD'],
    secondarySkills: ['Kubernetes', 'Helm'],
    resumeSnippet:
      'Rohan Jadhav — Platform engineer at Persistent Systems, AWS, Terraform, Kubernetes, CI/CD, Linux administration.',
    vendorSubmitted: true,
  },
  {
    email: 'pooja.shah@Stitch.com',
    name: 'Pooja Shah',
    role: 'SRE',
    status: 'SCREENING',
    source: 'Vendor: Demo Staffing Co',
    jobCode: 'REQ28062026003',
    location: 'Mumbai',
    totalExperience: '9 Years',
    currentCompany: 'Jio Platforms',
    primarySkills: ['Kubernetes', 'AWS', 'Prometheus', 'Grafana'],
    secondarySkills: ['Terraform', 'Python'],
    resumeSnippet:
      'Pooja Shah — SRE at Jio Platforms, Kubernetes, AWS, Prometheus, Grafana, Terraform, CI/CD pipelines.',
    vendorSubmitted: true,
  },
  {
    email: 'jayesh.mehta@Stitch.com',
    name: 'Jayesh Mehta',
    role: 'DevOps Consultant',
    status: 'APPLIED',
    source: 'Vendor: Demo Staffing Co',
    jobCode: 'REQ28062026003',
    location: 'Chennai',
    totalExperience: '3 Years',
    currentCompany: 'Cognizant',
    primarySkills: ['Docker', 'AWS', 'Linux'],
    secondarySkills: ['Jenkins', 'Bash'],
    resumeSnippet:
      'Jayesh Mehta — DevOps consultant at Cognizant, Docker, AWS, Linux, Jenkins, CI/CD.',
    vendorSubmitted: true,
  },
  {
    email: 'esha.banerjee@Stitch.com',
    name: 'Esha Banerjee',
    role: 'UX Designer',
    status: 'INTERVIEW',
    source: 'Referral',
    jobCode: 'REQ28062026004',
    location: 'Bangalore (Remote)',
    totalExperience: '5 Years',
    currentCompany: 'Razorpay',
    primarySkills: ['Figma', 'User Research', 'Wireframing'],
    secondarySkills: ['Accessibility', 'HTML', 'CSS'],
    resumeSnippet:
      'Esha Banerjee — UX designer at Razorpay, Figma, user research, wireframing, design systems, accessibility.',
    interviewProgress: 'l1-scheduled',
  },
  {
    email: 'tarun.bhatia@Stitch.com',
    name: 'Tarun Bhatia',
    role: 'Product Designer',
    status: 'HIRED',
    source: 'Recruiter Added',
    jobCode: 'REQ28062026004',
    location: 'Gurgaon',
    totalExperience: '10 Years',
    currentCompany: 'Paytm',
    primarySkills: ['Figma', 'Design Systems', 'Prototyping'],
    secondarySkills: ['Framer', 'CSS'],
    resumeSnippet:
      'Tarun Bhatia — Product designer at Paytm, Figma, design systems, prototyping, HTML CSS.',
    interviewProgress: 'all-rounds-complete',
    offerStatus: 'ACCEPTED',
  },
  {
    email: 'aadhya.krishnan@Stitch.com',
    name: 'Aadhya Krishnan',
    role: 'Product Designer',
    status: 'JOINED',
    source: 'LinkedIn',
    jobCode: 'REQ28062026004',
    location: 'Bangalore',
    totalExperience: '8 Years',
    currentCompany: 'Formerly PhonePe',
    primarySkills: ['Figma', 'Design Systems', 'User Research'],
    secondarySkills: ['Prototyping', 'Accessibility'],
    resumeSnippet:
      'Aadhya Krishnan — Ex-PhonePe product designer, 8 years fintech UX, design systems, accessibility.',
    interviewProgress: 'all-rounds-complete',
    offerStatus: 'ACCEPTED',
  },
  {
    email: 'anita.krishnan@Stitch.com',
    name: 'Anita Krishnan',
    role: 'Data Analyst',
    status: 'SHORTLISTED',
    source: 'LinkedIn',
    jobCode: 'REQ28062026005',
    location: 'Chennai',
    totalExperience: '4 Years',
    currentCompany: 'DataFirst',
    primarySkills: ['SQL', 'Python', 'Tableau', 'Excel'],
    secondarySkills: ['Statistics', 'Power BI'],
    resumeSnippet:
      'Anita Krishnan — Data analyst, SQL, Python, Tableau, Excel, hiring analytics and reporting.',
  },
  {
    email: 'chaitanya.joshi@Stitch.com',
    name: 'Chaitanya Joshi',
    role: 'Analytics Engineer',
    status: 'SCREENING',
    source: 'Vendor: Demo Staffing Co',
    jobCode: 'REQ28062026005',
    location: 'Pune',
    totalExperience: '6 Years',
    currentCompany: 'Mu Sigma',
    primarySkills: ['SQL', 'Python', 'dbt'],
    secondarySkills: ['Snowflake', 'Tableau'],
    resumeSnippet:
      'Chaitanya Joshi — Analytics engineer at Mu Sigma, SQL, Python, dbt, Snowflake, Tableau, statistics.',
    vendorSubmitted: true,
  },
  {
    email: 'yogesh.thakur@Stitch.com',
    name: 'Yogesh Thakur',
    role: 'BI Analyst',
    status: 'REJECTED',
    source: 'Recruiter Added',
    jobCode: 'REQ28062026005',
    location: 'Indore',
    totalExperience: '2 Years',
    currentCompany: 'Retail Solutions India',
    primarySkills: ['Excel', 'SQL'],
    secondarySkills: ['R'],
    resumeSnippet:
      'Yogesh Thakur — BI analyst, Excel, SQL, basic reporting for retail analytics.',
  },
  {
    email: 'oviya.ramesh@Stitch.com',
    name: 'Oviya Ramesh',
    role: 'Frontend Developer',
    status: 'SOURCED',
    source: 'LinkedIn',
    jobCode: null,
    location: 'Kochi',
    totalExperience: '3 Years',
    currentCompany: 'Tata Elxsi',
    primarySkills: ['React', 'TypeScript', 'CSS'],
    secondarySkills: ['Next.js'],
    resumeSnippet:
      'Oviya Ramesh — Frontend developer at Tata Elxsi, React, TypeScript, CSS, Next.js, REST APIs.',
  },
  {
    email: 'raj.malhotra@Stitch.com',
    name: 'Raj Malhotra',
    role: 'Engineering Manager',
    status: 'SOURCED',
    source: 'Referral',
    jobCode: null,
    location: 'Gurgaon',
    totalExperience: '12 Years',
    currentCompany: 'BigTech India',
    primarySkills: ['Leadership', 'System Design', 'TypeScript'],
    secondarySkills: ['Hiring', 'Agile'],
    resumeSnippet:
      'Raj Malhotra — Engineering manager, system design, TypeScript, team leadership, agile.',
  },
  {
    email: 'shreya.pandey@Stitch.com',
    name: 'Shreya Pandey',
    role: 'QA Engineer',
    status: 'SOURCED',
    source: 'Recruiter Added',
    jobCode: null,
    location: 'Lucknow',
    totalExperience: '5 Years',
    currentCompany: 'HCLTech',
    primarySkills: ['Selenium', 'Jest', 'API Testing'],
    secondarySkills: ['Cypress', 'Postman'],
    resumeSnippet:
      'Shreya Pandey — QA engineer at HCLTech, Selenium, Jest, API testing, Cypress, Postman.',
  },
  {
    email: 'bharat.choudhury@Stitch.com',
    name: 'Bharat Choudhury',
    role: 'Mobile Developer',
    status: 'APPLIED',
    source: 'Direct',
    jobCode: 'REQ28062026001',
    location: 'Kolkata',
    totalExperience: '4 Years',
    currentCompany: 'Dream11',
    primarySkills: ['React Native', 'TypeScript'],
    secondarySkills: ['Firebase'],
    resumeSnippet:
      'Bharat Choudhury — Mobile developer at Dream11, React Native, TypeScript, Node.js, REST APIs.',
  },
  {
    email: 'gauri.kulkarni@Stitch.com',
    name: 'Gauri Kulkarni',
    role: 'Technical Writer',
    status: 'SCREENING',
    source: 'Direct',
    jobCode: null,
    location: 'Nagpur',
    totalExperience: '6 Years',
    currentCompany: 'Zoho',
    primarySkills: ['Documentation', 'API Docs', 'Markdown'],
    secondarySkills: ['Confluence', 'Git'],
    resumeSnippet:
      'Gauri Kulkarni — Technical writer at Zoho, API documentation, Markdown, Confluence, Git.',
  },
]
